# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.

Inspired from:<https://github.com/rougier/numpy-100>.

#### 1. Import the numpy package under the name `np` (★☆☆)

In [2]:
import numpy as np
import pandas as pd

#### 2. Print the numpy version and the configuration (★☆☆)

In [ ]:
np.__version__

'1.21.6'

#### 3. Create a null vector of size 10 (★☆☆)

In [ ]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 4. How to find the memory size of any array (★☆☆)

In [ ]:
z=np.zeros((10,10))
print("%d bytes"%(z.size*z.itemsize))

800 bytes


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [ ]:
%run `python -c "import numpy; numpy.info(numpy.add)"`

ERROR:root:File `'`python.py'` not found.


#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [ ]:
z=np.zeros(10)
z[4]=1
print(z)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [ ]:
z=np.arange(10,50)
print(z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [ ]:
z=np.arange(50)
z=z[::-1]
print(z)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2
  1  0]


#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [ ]:
z=np.arange(0,9).reshape(3,3)
print(z)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [ ]:
nz=np.nonzero([1,2,0,0,4,0])
print(nz)

(array([0, 1, 4]),)


#### 11. Create a 3x3 identity matrix (★☆☆)

In [ ]:
identity=np.eye(3)
print(identity)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆)

In [ ]:
np.random.random((3,3,3))

array([[[0.37785237, 0.17276328, 0.61726934],
        [0.20657335, 0.54662015, 0.0031717 ],
        [0.68934133, 0.58245801, 0.32208603]],

       [[0.38304164, 0.55251437, 0.6796141 ],
        [0.15210413, 0.59500195, 0.13642365],
        [0.34922849, 0.29804594, 0.98288359]],

       [[0.58779273, 0.49615615, 0.30305787],
        [0.35228625, 0.22943438, 0.67239895],
        [0.74869523, 0.4447265 , 0.73453169]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [ ]:
z=np.random.random((10,10))
print(z)
print(z.max())
print(z.min())

[[0.22977159 0.77968416 0.24788245 0.18252458 0.53386923 0.87063139
  0.33527884 0.5714566  0.01131981 0.18829693]
 [0.39118911 0.10695902 0.79280923 0.28267483 0.91506599 0.13746614
  0.76894263 0.35012001 0.88095763 0.68980872]
 [0.28530649 0.89711464 0.95711838 0.15763672 0.24713247 0.35761754
  0.46586199 0.30677371 0.96548184 0.87147008]
 [0.32669273 0.24370382 0.29246493 0.0976755  0.56452737 0.61165361
  0.24664754 0.68419158 0.33067221 0.67518992]
 [0.05562133 0.36632967 0.92450668 0.73650465 0.69566816 0.16814719
  0.88603003 0.14838993 0.48333719 0.16795211]
 [0.9769813  0.03026407 0.54127108 0.03770475 0.17488089 0.0440303
  0.42703813 0.19334547 0.82375096 0.00956921]
 [0.13280359 0.02784426 0.13082901 0.07388032 0.56631141 0.36209643
  0.24219269 0.55613319 0.46249827 0.86919515]
 [0.86886008 0.92767525 0.20506473 0.46926553 0.04464378 0.62721781
  0.69414993 0.91802188 0.8650049  0.65088071]
 [0.45499052 0.6183317  0.88667342 0.88891873 0.27492716 0.66455574
  0.20229993 

#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [ ]:
z=np.random.random(30)
print(z.mean()*100)

62.456032779498294


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [ ]:
z=np.ones((10,10))
print(z)
z[1:-1,1:-1]=0
print(z)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [ ]:
z = np.ones((5,5))
#Z = np.pad(Z, pad_width=1, mode='constant', constant_values=0)
print(Z)
z[:,[0,-1]]=0
z[[0,-1],:]=0
print(z)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [ ]:
print(0*np.nan)
print(np.nan==np.nan)
print(np.inf>np.nan)
print(np.nan-np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3*0.1)

nan
False
False
nan
True
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [ ]:
np.diag(1+np.arange(4),k=-1)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)


In [ ]:
z=np.zeros((8,8),dtype="int")
print(z)
z[1::2,::2]=1
z[::2,1::2]=1
print(z)

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [ ]:
np.unravel_index(99,(6,7,8))

(1, 5, 3)

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [ ]:
z=np.tile(np.array([[0,1],[1,0]]),(4,4))
print(z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 22. Normalize a 5x5 random matrix (★☆☆)

In [ ]:
z=np.random.random((5,5))
z=(z-np.mean(z)/(np.std(z)))
print(z)

[[-2.08922217 -1.70267292 -1.58091215 -1.9776765  -1.73935337]
 [-1.86915354 -1.34852408 -1.79506644 -1.40827392 -1.35305409]
 [-1.72579213 -1.43218795 -1.96820399 -2.2692491  -1.91919267]
 [-1.71338677 -1.81860888 -1.58869245 -1.83110113 -1.47777683]
 [-1.45928874 -1.71183952 -2.01924992 -2.05446515 -1.87293945]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [ ]:
color=np.dtype([("r",np.ubyte),
           ("g",np.ubyte),
           ("b",np.ubyte),
           ("a",np.ubyte)])
print(color)

[('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')]


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [ ]:
np.dot(np.ones((5,3)),np.ones((3,2)))

array([[3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.]])

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [ ]:
z = np.arange(11)
print(z)
z[(3 < z) & (z < 8)] *= -1
print(z)

[ 0  1  2  3  4  5  6  7  8  9 10]
[ 0  1  2  3 -4 -5 -6 -7  8  9 10]


#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [ ]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

10
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [ ]:
#print(z**z) #illegal
print(2<<z>>2) #legal
print(z<-z) #legal
print(1j*z) #legal
print(z/1/1)#legal
#print(z<z>z)#illegal

[  0   1   2   4   0   0   0   0 128 256 512]
[False False False False  True  True  True  True False False False]
[ 0. +0.j  0. +1.j  0. +2.j  0. +3.j -0. -4.j -0. -5.j -0. -6.j -0. -7.j
  0. +8.j  0. +9.j  0.+10.j]
[ 0.  1.  2.  3. -4. -5. -6. -7.  8.  9. 10.]


#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [ ]:
print(np.array(0)/np.array(0))
print(np.array(0)//np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-9.22337204e+18]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  


#### 29. How to round away from zero a float array ? (★☆☆)

In [ ]:
z=np.random.uniform(-10,+10,10)
print(np.copysign(np.ceil(np.abs(z)),z))

[ 1. -7. 10.  1. -6. -8. -8.  4. -9. -6.]


#### 30. How to find common values between two arrays? (★☆☆)

In [ ]:
z1 = np.random.randint(0,10,15)
z2 = np.random.randint(0,20,15) 
print(np.intersect1d(z1,z2))

[1 2 3 5 6 7]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [ ]:
defaults = np.seterr(all="ignore")
z = np.ones(1)/0
#back to sanity
np.seterr(**defaults)
print(z)

# Equivalently with a context manager
with np.errstate(all="ignore"):
    np.arange(3) / 0

[inf]


#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [ ]:
print(np.sqrt(-1)==np.emath.sqrt(-1)) #false

False


#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [ ]:
today=np.datetime64("today")
print(f'today date is : {today}')
yesterday = np.datetime64("today")- np.timedelta64(1)
print(f'yesterday date is: {yesterday}')
tomorrow = np.datetime64("today")+np.timedelta64(1)
print(f'tomorrow date is: {tomorrow}')

today date is : 2022-08-27
yesterday date is: 2022-08-26
tomorrow date is: 2022-08-28


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [ ]:
np.arange("2016-07","2016-08",dtype="datetime64[D]")

array(['2016-07-01', '2016-07-02', '2016-07-03', '2016-07-04',
       '2016-07-05', '2016-07-06', '2016-07-07', '2016-07-08',
       '2016-07-09', '2016-07-10', '2016-07-11', '2016-07-12',
       '2016-07-13', '2016-07-14', '2016-07-15', '2016-07-16',
       '2016-07-17', '2016-07-18', '2016-07-19', '2016-07-20',
       '2016-07-21', '2016-07-22', '2016-07-23', '2016-07-24',
       '2016-07-25', '2016-07-26', '2016-07-27', '2016-07-28',
       '2016-07-29', '2016-07-30', '2016-07-31'], dtype='datetime64[D]')

#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [ ]:
A = np.ones(3)*1       #1,1,1
B = np.ones(3)*1       #1,1,1
np.add(A,B,out=B)      #add a,b #2,2,2
np.divide(A,2,out=A)   #divide by 2 #0.5 0.5 0.5
np.negative(A,out=A)   #negative the value a:-0.5 -0.5 -0.5
np.multiply(A,B,out=A) #mutiply the value A,B :-1,-1,-1

array([-1., -1., -1.])

#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [ ]:
z=np.random.uniform(0,10,10)
print(z-z%1)
print(z//1)
print(np.floor(z))
print(z.astype(int))
print(np.trunc(z))

[7. 9. 3. 7. 6. 0. 3. 2. 4. 1.]
[7. 9. 3. 7. 6. 0. 3. 2. 4. 1.]
[7. 9. 3. 7. 6. 0. 3. 2. 4. 1.]
[7 9 3 7 6 0 3 2 4 1]
[7. 9. 3. 7. 6. 0. 3. 2. 4. 1.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [ ]:
z=np.zeros((5,5))
z+= np.arange(5)
print(z)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [ ]:
def generate():
  for x in range(10):
    yield x
z = np.fromiter(generate(),dtype=float,count=-1)
print(z)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [ ]:
np.linspace(0,1,11,endpoint=False)[1:]

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

#### 40. Create a random vector of size 10 and sort it (★★☆)

In [ ]:
z=np.random.random(10)
z.sort()
print(z)

[0.28695744 0.36249496 0.40813707 0.4195934  0.42087291 0.44469241
 0.68434778 0.73014462 0.90678987 0.9357514 ]


#### 41. How to sum a small array faster than np.sum? (★★☆)

In [ ]:
z = np.arange(10)
#print(np.sum(z))
print(np.add.reduce(z))

45


#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [ ]:
x = np.random.randint(0,2,5)
y = np.random.randint(0,2,5)
# Assuming identical shape of the arrays and a tolerance for the comparison of values
equal = np.allclose(x,y)
print(equal)
# Checking both the shape and the element values, no tolerance (values have to be exactly equal)
equal = np.array_equal(x,y)
print(equal)

False
False


#### 43. Make an array immutable (read-only) (★★☆)

In [ ]:
z=np.zeros(10)
print(z)
z.flags.writeable=False
z[0]=1

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


ValueError: ignored

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [ ]:
z= np.random.random((10,2))
x,y = z[:,0],z[:,1]
r = np.sqrt(x**2+y**2)
t = np.arctan2(y,x)
print(r)
print(t)

[1.34419331 0.21901014 0.2561825  1.20558165 0.59891986 0.61980431
 0.86246786 0.90954199 0.76175097 0.92522068]
[0.83381861 1.31296458 0.09018665 0.79758091 0.47700205 0.36694589
 0.62915564 0.32084128 0.02417125 1.21692257]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [ ]:
z=np.random.random(10)
z[z.argmax()]= 0
print(z)

[0.34685032 0.58046826 0.72539718 0.16858124 0.30483828 0.67542107
 0.07947493 0.49854492 0.21100101 0.        ]


#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

In [ ]:
#copied
Z = np.zeros((5,5), [('x',float),('y',float)])
Z['x'], Z['y'] = np.meshgrid(np.linspace(0,1,5),
                             np.linspace(0,1,5))
print(Z)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

In [ ]:
#copied
X = np.arange(8)
Y = X + 0.5
C = 1.0 / np.subtract.outer(X, Y)
print(np.linalg.det(C))

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

In [ ]:
print("int dtypes:\n")
for dtype in [np.int8,np.int16,np.int32,np.int64]:
  print(np.iinfo(dtype).min)     #to see the info of  int types
  print(np.iinfo(dtype).max)
print("\n")
print("Float dtypes:\n")
for dtype in [np.float16,np.float32,np.float64]:
  print(np.finfo(dtype).min)  #to see the info of float types
  print(np.finfo(dtype).max)
  print(np.finfo(dtype).eps)

int dtypes:

-128
127
-32768
32767
-2147483648
2147483647
-9223372036854775808
9223372036854775807


Float dtypes:

-65500.0
65500.0
0.000977
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


#### 49. How to print all the values of an array? (★★☆)

In [ ]:
#np.set_printoptions(threshold=float("inf")) #print al values of an array
z=np.zeros((40,40))
print(z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [ ]:
Z = np.arange(100)
v = np.random.uniform(0,100)
index = (np.abs(Z-v)).argmin()
print(Z[index])

14


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

In [ ]:
Z = np.zeros(10, [ ('position', [ ('x', float, 1),
                                  ('y', float, 1)]),
                   ('color',    [ ('r', float, 1),
                                  ('g', float, 1),
                                  ('b', float, 1)])])
print(Z)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:5: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  """


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

In [ ]:
Z = np.random.random((10,2))
X,Y = np.atleast_2d(Z[:,0], Z[:,1])
D = np.sqrt( (X-X.T)**2 + (Y-Y.T)**2)
print(D)

[[0.         0.19553139 0.94276025 0.54677705 0.81305753 0.61640933
  0.90908681 0.6560289  0.3322248  0.47000262]
 [0.19553139 0.         0.76215253 0.36213408 0.61752715 0.54591696
  0.71653478 0.55524736 0.35194736 0.38278569]
 [0.94276025 0.76215253 0.         0.59137804 0.33017983 0.61480537
  0.18461985 0.51095902 0.82190049 0.59904504]
 [0.54677705 0.36213408 0.59137804 0.         0.3222912  0.71496171
  0.46888032 0.66853739 0.66176324 0.57000059]
 [0.81305753 0.61752715 0.33017983 0.3222912  0.         0.73410843
  0.16219262 0.65001826 0.81675235 0.64189049]
 [0.61640933 0.54591696 0.61480537 0.71496171 0.73410843 0.
  0.71023365 0.1050082  0.32077894 0.16403924]
 [0.90908681 0.71653478 0.18461985 0.46888032 0.16219262 0.71023365
  0.         0.61374623 0.85535916 0.65253882]
 [0.6560289  0.55524736 0.51095902 0.66853739 0.65001826 0.1050082
  0.61374623 0.         0.39343061 0.18622553]
 [0.3322248  0.35194736 0.82190049 0.66176324 0.81675235 0.32077894
  0.85535916 0.393430

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

In [ ]:
Z = (np.random.rand(10)*100).astype(np.float32)
Y = Z.view(np.int32)
Y[:] = Z
print(Y)

[77 45 77 95 98 85  7  3 48 24]


#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [ ]:
from io import StringIO
s = StringIO('''1, 2, 3, 4, 5
                6,  ,  , 7, 8
                 ,  , 9,10,11
''')
z=np.genfromtxt(s,delimiter=",",dtype=int)
print(z)

[[ 1  2  3  4  5]
 [ 6 -1 -1  7  8]
 [-1 -1  9 10 11]]


#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

In [ ]:
Z = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(Z):
    print(index, value)
for index in np.ndindex(Z.shape):
    print(index, Z[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 56. Generate a generic 2D Gaussian-like array (★★☆)

In [ ]:
X, Y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
D = np.sqrt(X*X+Y*Y)
sigma, mu = 1.0, 0.0
G = np.exp(-( (D-mu)**2 / ( 2.0 * sigma**2 ) ) )
print(G)

[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0

#### 57. How to randomly place p elements in a 2D array? (★★☆)

In [ ]:
n = 10
p = 3
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace=False),1)
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### 58. Subtract the mean of each row of a matrix (★★☆)

In [ ]:
X = np.random.rand(5, 10)

# Recent versions of numpy
Y = X - X.mean(axis=1, keepdims=True)

# Older versions of numpy
Y = X - X.mean(axis=1).reshape(-1, 1)

print(Y)

[[ 4.99153665e-01 -3.04740326e-01  3.41215276e-01  3.17522441e-01
   6.88804504e-02 -2.71162641e-01 -3.32676779e-01  6.49220096e-02
  -3.83465956e-01  3.51859434e-04]
 [ 2.28513802e-01 -1.72565050e-01  1.00272285e-01 -7.09023122e-02
  -5.96174654e-02  3.39634686e-01 -6.87868730e-02  3.17167361e-01
  -3.51403439e-01 -2.62312994e-01]
 [ 3.12076417e-01 -4.43161616e-01 -8.53208419e-02 -6.48233731e-02
  -1.01942106e-01  1.97823068e-01  2.73365761e-01  4.19879218e-01
  -6.46278414e-02 -4.43268685e-01]
 [-4.38584943e-01 -1.66309292e-01  4.51298449e-01  2.14777430e-01
  -1.89256491e-01 -3.19741248e-01  6.08893514e-02 -9.53292765e-02
   4.37226625e-01  4.50293947e-02]
 [ 1.90410550e-01 -3.04544539e-01  1.45856106e-01  5.92675222e-04
  -2.20842182e-01 -4.35698941e-01  1.88914022e-01  2.95776134e-01
  -7.21804125e-02  2.11716588e-01]]


#### 59. How to sort an array by the nth column? (★★☆)

In [ ]:
Z = np.random.randint(0,10,(3,3))
print(Z)
print(Z[Z[:,1].argsort()])

[[3 6 4]
 [4 5 1]
 [9 9 4]]
[[4 5 1]
 [3 6 4]
 [9 9 4]]


#### 60. How to tell if a given 2D array has null columns? (★★☆)

In [ ]:
Z = np.random.randint(0,3,(3,10))
print((~Z.any(axis=0)).any())

True


#### 61. Find the nearest value from a given value in an array (★★☆)

In [ ]:
Z=np.random.uniform(0,10,100)
z = 0.5
n = Z.flat[np.abs(Z-z).argmin()]
print(n)

0.4606542184159146


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

In [ ]:
a = np.arange(3).reshape(1,3)
b = np.arange(3).reshape(3,1)
it = np.nditer([a,b,None])
for x,y,z in it: z[...] = x + y
print(it.operands[2])

[[0 1 2]
 [1 2 3]
 [2 3 4]]


#### 63. Create an array class that has a name attribute (★★☆)

In [ ]:
class NamedArray(np.ndarray):
  def __new__(cls,array,name="no name"):
    obj = np.asarray(array).view(cls)
    obj.name = name
    return obj
  
  def __array_finalize__(self,obj):
    if obj is None: return 
    self.info  = getattr(obj,"name","no name")

Z = NamedArray(np.arange(10),"arange_10")
print(Z.name)

arange_10


#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

In [ ]:
Z=np.ones(10)
I = np.random.randint(0,len(Z),20)
Z += np.bincount(I,minlength=len(Z))
print(Z)

[5. 3. 3. 4. 4. 2. 3. 2. 2. 2.]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

In [ ]:
x = [1,2,3,4,5,6]
i = [1,2,9,3,5,1]
f = np.bincount(i,x)
print(f)

[0. 7. 2. 4. 0. 5. 0. 0. 0. 3.]


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

In [ ]:
w,h = 256,256
i = np.random.randint(0,4,(h,w,3)).astype(np.ubyte)
colors = np.unique(i.reshape(-1,3),axis=0)
n = len(colors)
print(n)

64


#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

In [ ]:
A = np.random.randint(0,10,(3,4,3,4))
sum = A.sum(axis=(-2,-1))
print(sum,"\n")
sum = A.reshape(A.shape[:-2]+(-1,)).sum(axis=-1)
print(sum)

[[68 69 54 57]
 [47 65 53 40]
 [61 63 53 51]] 

[[68 69 54 57]
 [47 65 53 40]
 [61 63 53 51]]


#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

In [ ]:
D=np.random.uniform(0,1,100) #uniform gives random floating numbers
S=np.random.randint(0,10,100) #randint gives random integers values
D_sum= np.bincount(S,weights=D)
D_counts = np.bincount(S)
print(f"D_counts are:{D_counts}")
print(f"D_sums are:{D_sum}")
b_means = D_sum/D_counts
print(f"b_means are:{b_means}\n")


# Pandas solution as a reference due to more intuitive code
import pandas as pd
print(pd.Series(D).groupby(S).mean())

D_counts are:[11 17 12  6 10  9 11 12  6  6]
D_sums are:[5.17699705 8.40384031 7.03053326 2.52413598 5.2879457  3.61783663
 5.18953869 6.43687896 2.02164688 3.26381806]
b_means are:[0.4706361  0.49434355 0.58587777 0.42068933 0.52879457 0.40198185
 0.47177624 0.53640658 0.33694115 0.54396968]

0    0.470636
1    0.494344
2    0.585878
3    0.420689
4    0.528795
5    0.401982
6    0.471776
7    0.536407
8    0.336941
9    0.543970
dtype: float64


#### 69. How to get the diagonal of a dot product? (★★★)

In [ ]:
x=np.random.uniform(0,1,(5,5))
y=np.random.uniform(0,1,(5,5))
#slow version
np.diag(np.dot(x,y))
#fast version
np.sum(x*y.T,axis=1)
#faster version
np.einsum("ij,ji->i", x,y)

array([1.01739356, 1.15620085, 0.76056056, 1.00930766, 1.97566796])

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

In [ ]:
Z=np.array([1,2,3,4,5])
nz = 3
Z0 = np.zeros(len(Z)+(len(Z)-1)*(nz))
Z0[::nz+1]=Z
print(Z0)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

In [ ]:
A = np.ones((5,5,3))
B = 2*np.ones((5,5))
print(A * B[:,:,None])

[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


#### 72. How to swap two rows of an array? (★★★)

In [18]:
A=np.arange(25).reshape(5,5)
print(A)
A[[0,1]]=A[[1,0]]
print("Swapping two rows of an array:")
print(A)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
Swapping two rows of an array:
[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

In [20]:
faces=np.random.randint(0,100,(10,3))
F = np.roll(faces.repeat(2,axis=1),-1,axis=1)
F = F.reshape(len(F)*3,2)
F = np.sort(F,axis=1)
G = F.view( dtype=[('p0',F.dtype),('p1',F.dtype)] )
G = np.unique(G)
print(G)

[( 8, 77) ( 8, 85) (11, 18) (11, 43) (11, 60) (11, 93) (18, 60) (21, 36)
 (21, 47) (21, 48) (21, 60) (29, 31) (29, 60) (31, 60) (35, 59) (35, 70)
 (36, 47) (40, 52) (40, 60) (43, 93) (46, 61) (46, 95) (48, 60) (52, 60)
 (59, 70) (61, 95) (69, 70) (69, 90) (70, 90) (77, 85)]


#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

In [23]:
C=np.bincount([1,1,2,3,4,4,6])
A=np.repeat(np.arange(len(C)), C)
print(A)

[1 1 2 3 4 4 6]


#### 75. How to compute averages using a sliding window over an array? (★★★)

In [24]:
def moving_average(a, n=3) :
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n
Z = np.arange(20)
print(moving_average(Z, n=3))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]


#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

In [27]:
#from numpy.lib.stride_tricks import sliding_window_view

#Z = np.arange(20)
#print(sliding_window_view(Z, window_shape=3).mean(axis=-1))

from numpy.lib import stride_tricks

def rolling(a, window):
    shape = (a.size - window + 1, window)
    strides = (a.strides[0], a.strides[0])
    return stride_tricks.as_strided(a, shape=shape, strides=strides)
Z = rolling(np.arange(10), 3)
print(Z)

Z = np.arange(10)
print(sliding_window_view(Z, window_shape=3))

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]
[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

In [28]:
Z = np.random.randint(0,2,100)
np.logical_not(Z, out=Z)

Z = np.random.uniform(-1.0,1.0,100)
np.negative(Z, out=Z)

array([ 6.07856478e-02,  6.88704908e-01,  1.34045897e-01, -3.35493975e-01,
        5.47195746e-02,  2.20045130e-01,  8.06501295e-01,  8.30254398e-01,
       -8.30899930e-01,  1.99823396e-01, -1.45532792e-01,  2.95326713e-01,
        8.31243760e-01, -7.33525545e-01, -8.74805501e-01,  1.36002845e-01,
        2.84108253e-01, -6.02340650e-01,  1.69949849e-01,  8.88610198e-01,
       -7.82120529e-01, -8.86677271e-01,  7.73962390e-01, -3.31913141e-01,
        9.30266197e-01, -5.09710309e-01,  5.21676469e-01, -3.73090729e-01,
        8.28726212e-01, -2.57525356e-01, -3.77982548e-01, -1.71266301e-01,
       -9.73985696e-01,  3.22600043e-02,  3.01149080e-01,  8.50789441e-01,
       -8.58164584e-01,  5.95079180e-01, -6.60665178e-01,  8.68926355e-01,
        1.43240875e-02,  2.34334824e-01,  2.05349036e-01, -9.20126190e-01,
       -2.05021659e-02,  8.38883182e-01, -7.59290163e-01,  7.74837226e-01,
        3.23744468e-01, -7.47835671e-01,  6.46822600e-01,  5.54165903e-01,
       -8.68807183e-01,  

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

In [29]:
def distance(P0, P1, p):
    T = P1 - P0
    L = (T**2).sum(axis=1)
    U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1]) / L
    U = U.reshape(len(U),1)
    D = P0 + U*T - p
    return np.sqrt((D**2).sum(axis=1))

P0 = np.random.uniform(-10,10,(10,2))
P1 = np.random.uniform(-10,10,(10,2))
p  = np.random.uniform(-10,10,( 1,2))
print(distance(P0, P1, p))

[12.04852832 14.95935993 15.9151079   8.24628075 14.07042572 11.62192273
  2.15630441  3.10847717 10.5391333   3.18749203]


#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

In [30]:
P0 = np.random.uniform(-10, 10, (10,2))
P1 = np.random.uniform(-10,10,(10,2))
p = np.random.uniform(-10, 10, (10,2))
print(np.array([distance(P0,P1,p_i) for p_i in p]))

[[ 4.4464143   2.61445835  2.71960367  5.18262736  4.63921841  0.64793141
   5.79843816  5.76117444  9.10218656  2.47351895]
 [14.44132774  2.57357751  9.33168218  5.85633848  9.68712815  2.81645513
  10.48566625  0.36302656  2.70299912 10.53597925]
 [18.70700581  9.41066282  9.42851728  3.55951565  3.69121726  3.58620936
   4.38426798  5.98592712  1.77422112  5.79116249]
 [14.01678288  0.33563558 10.96290167  8.36360649 12.93393497  6.01625641
  13.72721955  2.31017458  4.73561996 13.66980319]
 [18.94292792  8.92706175 10.06830676  4.31352984  4.38424068  2.94950933
   5.06536664  5.82852528  2.47302086  6.55783954]
 [10.52819877  5.47055074  2.49242085  1.41105642  4.28523765  1.85237646
   5.24534891  0.77630391  4.42683239  3.93894761]
 [ 1.24903513  6.05263359  0.18426812  0.16062186 13.34541869  8.22410458
  14.55867148 12.61052507  5.3223544  10.26028031]
 [ 6.1673459   9.5033742   5.72157195 10.33236677  2.69116362  7.98026945
   1.54530744  0.76216695 13.07267291  4.37350039]


#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

In [32]:
Z = np.random.randint(0,10,(10,10))
shape = (5,5)
fill  = 0
position = (1,1)

R = np.ones(shape, dtype=Z.dtype)*fill
P  = np.array(list(position)).astype(int)
Rs = np.array(list(R.shape)).astype(int)
Zs = np.array(list(Z.shape)).astype(int)

R_start = np.zeros((len(shape),)).astype(int)
R_stop  = np.array(list(shape)).astype(int)
Z_start = (P-Rs//2)
Z_stop  = (P+Rs//2)+Rs%2

R_start = (R_start - np.minimum(Z_start,0)).tolist()
Z_start = (np.maximum(Z_start,0)).tolist()
R_stop = np.maximum(R_start, (R_stop - np.maximum(Z_stop-Zs,0))).tolist()
Z_stop = (np.minimum(Z_stop,Zs)).tolist()

r = [slice(start,stop) for start,stop in zip(R_start,R_stop)]
z = [slice(start,stop) for start,stop in zip(Z_start,Z_stop)]
R[r] = Z[z]
print(Z)
print(R)

[[5 5 9 2 4 9 7 7 5 1]
 [1 9 6 7 1 5 5 0 0 4]
 [4 4 5 9 0 5 6 2 3 5]
 [6 1 5 5 5 3 5 7 0 5]
 [4 8 3 4 0 6 0 6 9 3]
 [7 0 3 8 9 5 7 5 9 8]
 [7 9 0 4 7 4 3 7 3 0]
 [3 7 6 0 7 5 6 8 1 4]
 [5 4 3 8 2 8 4 1 2 9]
 [2 9 5 1 7 4 8 6 4 7]]
[[0 0 0 0 0]
 [0 5 5 9 2]
 [0 1 9 6 7]
 [0 4 4 5 9]
 [0 6 1 5 5]]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:23: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.


#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

In [ ]:
Z = np.arange(1,15,dtype=np.uint32)
R = stride_tricks.as_strided(Z,(11,4),(4,4))
print(R)

# Author: Jeff Luo (@Jeff1999)

Z = np.arange(1, 15, dtype=np.uint32)
print(sliding_window_view(Z, window_shape=4))

#### 82. Compute a matrix rank (★★★)

In [33]:
Z = np.random.uniform(0,1,(10,10))
U, S, V = np.linalg.svd(Z) # Singular Value Decomposition
rank = np.sum(S > 1e-10)
print(rank)

10


#### 83. How to find the most frequent value in an array?

In [38]:
z =np.random.randint(0,10,50)
print(np.bincount(z).argmax())

6


#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

In [39]:
Z = np.random.randint(0,5,(10,10))
n = 3
i = 1 + (Z.shape[0]-3)
j = 1 + (Z.shape[1]-3)
C = stride_tricks.as_strided(Z, shape=(i, j, n, n), strides=Z.strides + Z.strides)
print(C)

[[[[2 0 1]
   [2 1 0]
   [3 0 2]]

  [[0 1 0]
   [1 0 4]
   [0 2 3]]

  [[1 0 2]
   [0 4 3]
   [2 3 0]]

  [[0 2 0]
   [4 3 4]
   [3 0 2]]

  [[2 0 3]
   [3 4 0]
   [0 2 4]]

  [[0 3 4]
   [4 0 0]
   [2 4 3]]

  [[3 4 2]
   [0 0 1]
   [4 3 2]]

  [[4 2 3]
   [0 1 4]
   [3 2 0]]]


 [[[2 1 0]
   [3 0 2]
   [1 1 3]]

  [[1 0 4]
   [0 2 3]
   [1 3 2]]

  [[0 4 3]
   [2 3 0]
   [3 2 1]]

  [[4 3 4]
   [3 0 2]
   [2 1 3]]

  [[3 4 0]
   [0 2 4]
   [1 3 1]]

  [[4 0 0]
   [2 4 3]
   [3 1 2]]

  [[0 0 1]
   [4 3 2]
   [1 2 1]]

  [[0 1 4]
   [3 2 0]
   [2 1 1]]]


 [[[3 0 2]
   [1 1 3]
   [0 1 3]]

  [[0 2 3]
   [1 3 2]
   [1 3 1]]

  [[2 3 0]
   [3 2 1]
   [3 1 2]]

  [[3 0 2]
   [2 1 3]
   [1 2 4]]

  [[0 2 4]
   [1 3 1]
   [2 4 2]]

  [[2 4 3]
   [3 1 2]
   [4 2 1]]

  [[4 3 2]
   [1 2 1]
   [2 1 0]]

  [[3 2 0]
   [2 1 1]
   [1 0 0]]]


 [[[1 1 3]
   [0 1 3]
   [1 0 0]]

  [[1 3 2]
   [1 3 1]
   [0 0 4]]

  [[3 2 1]
   [3 1 2]
   [0 4 4]]

  [[2 1 3]
   [1 2 4]
   [4 4 0]]

  [[1 3 1]
   

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

In [40]:
class Symetric(np.ndarray):
    def __setitem__(self, index, value):
        i,j = index
        super(Symetric, self).__setitem__((i,j), value)
        super(Symetric, self).__setitem__((j,i), value)

def symetric(Z):
    return np.asarray(Z + Z.T - np.diag(Z.diagonal())).view(Symetric)

S = symetric(np.random.randint(0,10,(5,5)))
S[2,3] = 42
print(S)

[[ 3 11 18 15  2]
 [11  2 10  7  7]
 [18 10  6 42  5]
 [15  7 42  4 10]
 [ 2  7  5 10  2]]


#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

In [41]:
p, n = 10, 20
M = np.ones((p,n,n))
V = np.ones((p,n,1))
S = np.tensordot(M, V, axes=[[0, 2], [0, 1]])
print(S)

[[200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]]


#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

In [43]:
Z = np.ones((16,16))
k = 4
S = np.add.reduceat(np.add.reduceat(Z, np.arange(0, Z.shape[0], k), axis=0),
                                       np.arange(0, Z.shape[1], k), axis=1)
print(S)

Z = np.ones((16, 16))
k = 4
print(sliding_window_view(Z, window_shape=(k, k))[::k, ::k].sum(axis=(-2, -1)))

[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]
[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


#### 88. How to implement the Game of Life using numpy arrays? (★★★)

In [44]:
def iterate(Z):
    # Count neighbours
    N = (Z[0:-2,0:-2] + Z[0:-2,1:-1] + Z[0:-2,2:] +
         Z[1:-1,0:-2]                + Z[1:-1,2:] +
         Z[2:  ,0:-2] + Z[2:  ,1:-1] + Z[2:  ,2:])

    # Apply rules
    birth = (N==3) & (Z[1:-1,1:-1]==0)
    survive = ((N==2) | (N==3)) & (Z[1:-1,1:-1]==1)
    Z[...] = 0
    Z[1:-1,1:-1][birth | survive] = 1
    return Z

Z = np.random.randint(0,2,(50,50))
for i in range(100): Z = iterate(Z)
print(Z)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


#### 89. How to get the n largest values of an array (★★★)

In [45]:
Z = np.arange(10000)
np.random.shuffle(Z)
n = 5

# Slow
print (Z[np.argsort(Z)[-n:]])

# Fast
print (Z[np.argpartition(-Z,n)[:n]])

[9995 9996 9997 9998 9999]
[9996 9999 9998 9997 9995]


#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

In [46]:
def cartesian(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = (len(x) for x in arrays)

    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(arrays), -1).T

    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]

    return ix

print (cartesian(([1, 2, 3], [4, 5], [6, 7])))

[[1 4 6]
 [1 4 7]
 [1 5 6]
 [1 5 7]
 [2 4 6]
 [2 4 7]
 [2 5 6]
 [2 5 7]
 [3 4 6]
 [3 4 7]
 [3 5 6]
 [3 5 7]]


#### 91. How to create a record array from a regular array? (★★★)

In [47]:
Z = np.array([("Hello", 2.5, 3),
              ("World", 3.6, 2)])
R = np.core.records.fromarrays(Z.T,
                               names='col1, col2, col3',
                               formats = 'S8, f8, i8')
print(R)

[(b'Hello', 2.5, 3) (b'World', 3.6, 2)]


#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

In [48]:
x = np.random.rand(int(5e7))

%timeit np.power(x,3)
%timeit x*x*x
%timeit np.einsum('i,i,i->i',x,x,x)

2.11 s ± 7.43 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
61.4 ms ± 1.01 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
52.6 ms ± 982 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

In [49]:
A = np.random.randint(0,5,(8,3))
B = np.random.randint(0,5,(2,2))

C = (A[..., np.newaxis, np.newaxis] == B)
rows = np.where(C.any((3,1)).all(1))[0]
print(rows)

[0 1 2 3 5]


#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

In [50]:
Z = np.random.randint(0,5,(10,3))
print(Z)
# solution for arrays of all dtypes (including string arrays and record arrays)
E = np.all(Z[:,1:] == Z[:,:-1], axis=1)
U = Z[~E]
print(U)
# soluiton for numerical arrays only, will work for any number of columns in Z
U = Z[Z.max(axis=1) != Z.min(axis=1),:]
print(U)

[[0 3 4]
 [4 0 2]
 [2 1 3]
 [4 2 2]
 [1 3 0]
 [4 0 0]
 [4 2 2]
 [1 1 1]
 [2 3 4]
 [1 2 4]]
[[0 3 4]
 [4 0 2]
 [2 1 3]
 [4 2 2]
 [1 3 0]
 [4 0 0]
 [4 2 2]
 [2 3 4]
 [1 2 4]]
[[0 3 4]
 [4 0 2]
 [2 1 3]
 [4 2 2]
 [1 3 0]
 [4 0 0]
 [4 2 2]
 [2 3 4]
 [1 2 4]]


#### 95. Convert a vector of ints into a matrix binary representation (★★★)

In [51]:
I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128])
B = ((I.reshape(-1,1) & (2**np.arange(8))) != 0).astype(int)
print(B[:,::-1])

# Author: Daniel T. McDonald

I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128], dtype=np.uint8)
print(np.unpackbits(I[:, np.newaxis], axis=1))

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]
[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

In [53]:
Z = np.random.randint(0,2,(6,3))
T = np.ascontiguousarray(Z).view(np.dtype((np.void, Z.dtype.itemsize * Z.shape[1])))
_, idx = np.unique(T, return_index=True)
uZ = Z[idx]
print(uZ)

uZ = np.unique(Z, axis=0)
print(uZ)

[[0 0 0]
 [0 1 1]
 [1 0 1]]
[[0 0 0]
 [0 1 1]
 [1 0 1]]


#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

In [54]:
A = np.random.uniform(0,1,10)
B = np.random.uniform(0,1,10)

np.einsum('i->', A)       # np.sum(A)
np.einsum('i,i->i', A, B) # A * B
np.einsum('i,i', A, B)    # np.inner(A, B)
np.einsum('i,j->ij', A, B)    # np.outer(A, B)

array([[0.16922219, 0.09776101, 0.06720094, 0.07270679, 0.03224544,
        0.18621726, 0.08321814, 0.10034522, 0.04938002, 0.09970691],
       [0.59266948, 0.34238986, 0.23535887, 0.25464212, 0.11293369,
        0.65219156, 0.29145618, 0.35144061, 0.17294441, 0.34920505],
       [0.1102619 , 0.06369917, 0.04378683, 0.04737434, 0.0210105 ,
        0.12133555, 0.05422333, 0.065383  , 0.03217506, 0.06496709],
       [0.21593179, 0.12474551, 0.08575009, 0.0927757 , 0.04114599,
        0.23761792, 0.10618845, 0.12804304, 0.06301015, 0.12722854],
       [0.32306107, 0.18663494, 0.1282929 , 0.1388041 , 0.06155957,
        0.35550624, 0.15887125, 0.19156846, 0.0942711 , 0.19034987],
       [0.32160026, 0.18579103, 0.12771279, 0.13817646, 0.06128121,
        0.35389873, 0.15815288, 0.19070224, 0.09384483, 0.18948915],
       [0.45206775, 0.26116313, 0.17952359, 0.19423219, 0.08614191,
        0.49746913, 0.22231268, 0.26806673, 0.13191601, 0.26636152],
       [0.04569278, 0.02639708, 0.0181453

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

In [55]:
phi = np.arange(0, 10*np.pi, 0.1)
a = 1
x = a*phi*np.cos(phi)
y = a*phi*np.sin(phi)

dr = (np.diff(x)**2 + np.diff(y)**2)**.5 # segment lengths
r = np.zeros_like(x)
r[1:] = np.cumsum(dr)                # integrate path
r_int = np.linspace(0, r.max(), 200) # regular spaced path
x_int = np.interp(r_int, r, x)       # integrate path
y_int = np.interp(r_int, r, y)

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

In [56]:
X = np.asarray([[1.0, 0.0, 3.0, 8.0],
                [2.0, 0.0, 1.0, 1.0],
                [1.5, 2.5, 1.0, 0.0]])
n = 4
M = np.logical_and.reduce(np.mod(X, 1) == 0, axis=-1)
M &= (X.sum(axis=-1) == n)
print(X[M])

[[2. 0. 1. 1.]]


#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)

In [57]:
X = np.random.randn(100) # random 1D array
N = 1000 # number of bootstrap samples
idx = np.random.randint(0, X.size, (N, X.size))
means = X[idx].mean(axis=1)
confint = np.percentile(means, [2.5, 97.5])
print(confint)

[-0.24083914  0.09659645]
