In [1]:
import numpy as np

In [25]:
x =np.array([[1,2,3,5.5],[1,2,3,4]],dtype=int)
print(x)


[[1 2 3 5]
 [1 2 3 4]]


In [19]:
print(x.shape)
print(x.ndim)
print(x.size)

(2, 4)
2
8


In [31]:
np.zeros((3,3,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [38]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [39]:
np.random.rand(2,3)

array([[0.20822248, 0.74857709, 0.89290903],
       [0.91054269, 0.77031994, 0.08755822]])

In [40]:
#choice
np.full((2,2),7)

array([[7, 7],
       [7, 7]])

In [42]:
#identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [50]:
np.arange(2,8)
np.arange(2,8,2)

array([2, 4, 6])

In [49]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [54]:
x.reshape(4,2)

array([[1, 2],
       [3, 5],
       [1, 2],
       [3, 4]])

In [59]:
a = np.ones((2,2))
print(a)
print(a.ndim)
#making 1day array
b = a.flatten()
c = a.ravel()
print(b.ndim)
print(c)
c[0]=0
print(c)

[[1. 1.]
 [1. 1.]]
2
1
[1. 1. 1. 1.]
[0. 1. 1. 1.]


In [61]:
a = np.array([[1,2,3],[4,5,6]])
print(a)
print("transpose of array a:")
b = np.transpose(a)
print(b)

[[1 2 3]
 [4 5 6]]
transpose of array a:
[[1 4]
 [2 5]
 [3 6]]


In [69]:
#Slicing 1-D NumPy arrays
a = np.array([1,2,3,4,5,6])
a[2:]
a[:3]
a[1:3]
a[:-1:2]

array([1, 3, 5])

In [101]:
#Slicing 2-D NumPy arrays
a = np.array([[1,2,3,4],[4,5,6,7]])
print(a)
a[:3,1:-1]
a[::2,::2]
a[1:,1::]
a[0,2]
a[1,-1]
a[0,-1]
a[0,-2]

[[1 2 3 4]
 [4 5 6 7]]


3

In [110]:
#Slicing 3-D NumPy arrays
a = np.array([[[1,2],[3,4],[5,6]],[[7,8],[9,10],[11,12]]])
print(a)
a[:,:,:1]
a[:,1:,::]
a[:,1:,1:]
a[:,2:,::]

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


array([[[ 5,  6]],

       [[11, 12]]])

In [121]:
#Stacking and Concatenating NumPy arrays
a = np.ones(5)
b= np.zeros(5)
v = np.hstack((a,b))
print(v)
h = np.vstack((a,b))
print(h)
c = np.concatenate((a,b))
print(c)

[1. 1. 1. 1. 1. 0. 0. 0. 0. 0.]
[[1. 1. 1. 1. 1.]
 [0. 0. 0. 0. 0.]]
[1. 1. 1. 1. 1. 0. 0. 0. 0. 0.]


In [129]:
a = np.array([[1,2],[3,4]])
np.append(a,[[6,7]],axis=0)

array([[1, 2],
       [3, 4],
       [6, 7]])

In [162]:
np.mean(a)
np.max(a)
np.min(a)
np.average(a)
np.sum(a)
np.diff(a)


array([0.6, 0.6, 0.6, 0.6, 0.6])

In [141]:
#Mean, Median and Standard deviation
a = np.arange(2,15,2)
np.mean(a)
np.median(a)
np.std(a)

4.0

In [142]:
a = np.array([1,4,2,5,3,6,8,7,9])
np.sort(a)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [161]:
a = np.linspace(2,5,6)
b = np.linspace(3,2,6)
c = np.vstack((a,b))
np.sort(c,axis=1)


array([[2. , 2.6, 3.2, 3.8, 4.4, 5. ],
       [2. , 2.2, 2.4, 2.6, 2.8, 3. ]])

In [166]:
c.size
c.resize(6,2)
print(c)

[[2.  2.6]
 [3.2 3.8]
 [4.4 5. ]
 [3.  2.8]
 [2.6 2.4]
 [2.2 2. ]]


In [167]:
c.nbytes

96

In [175]:
np.split(a,3,axis=0)

[array([2. , 2.6]), array([3.2, 3.8]), array([4.4, 5. ])]

In [185]:
np.random.randint(40)
np.random.rand(3,4)
np.random.randn(2,5,3)


array([[[ 1.56956983,  0.57000077,  0.94475253],
        [-0.47337479, -0.89391931,  1.4634256 ],
        [ 0.30446307,  0.44386858,  0.14428814],
        [ 0.63721593, -0.18073431,  0.54742856],
        [-0.44288097, -0.53548097,  0.30859408]],

       [[-1.25319604,  0.23451797, -1.46539329],
        [ 0.96652519, -1.64479421, -1.72086647],
        [ 0.70353019,  0.01885237,  0.41704376],
        [ 0.90827188, -0.39065412, -0.86422773],
        [-0.45822421, -0.38635218, -1.26226887]]])

In [190]:
a = np.genfromtxt("/content/odd_numbers.csv",delimiter=",",dtype=int)
a

array([[ 1,  3,  5,  7,  9],
       [11, 13, 15, 17, 19],
       [21, 23, 25, 27, 29],
       [31, 33, 35, 37, 39],
       [43, 45, 47, 49, -1]])

In [192]:
print(a.shape)
print(a.size)
print(a.ndim)
a.reshape(25)

(5, 5)
25
2


array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 43, 45, 47, 49, -1])

In [232]:
x = np.savetxt("even.txt",a)